---
- name: MySQL | Set debconf vars root passwd
  shell: sudo echo mysql-server mysql-server/root_password password {{mysql_root_passwd}} | sudo /usr/bin/debconf-set-selections

- name: MySQL | Set debconf vars root passwd again
  shell: sudo echo mysql-server mysql-server/root_password_again password {{mysql_root_passwd}} | sudo /usr/bin/debconf-set-selections

- name: Install mysql packages
  apt: name={{item}} state=installed
  with_items:
  - mysql-server
  - mysql-client
  - mysql-common
  - python-mysqldb

- name: copy the my.cnf file
  copy: src=my.cnf dest=/etc/mysql/my.cnf 

- name: Stop the MySQL service
  service: name=mysql state=stopped

- name: Start the MySQL service
  service: name=mysql state=started 

# - debug: var=mysql_root_passwd

# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_passwd }} login_user=root login_password={{mysql_root_passwd}} priv=*.*:ALL,GRANT
  with_items:
  - "{{ ansible_hostname }}"
  - 127.0.0.1
  - ::1
  - localhost

- name: Stop the MySQL service
  service: name=mysql state=stopped

- name: Start the MySQL service
  service: name=mysql state=started 

- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf dest=~root/.my.cnf owner=root mode=0600 backup=yes

